image: docker:latest

stages:
    - build
    - test
    - staging
    - release

variables:
    CONTAINER_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    MYSQL_DATABASE: pastell_test
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"

build:
  stage: build
  tags:
    - docker-build
  script:
    - date=$(date)
    - sed "s/%CI_BUILD_ID%/${CI_BUILD_ID}/" ./manifest.yml | sed "s/%BUILD_DATE%/$date/" > /tmp/manifest.yml
    - cp /tmp/manifest.yml ./manifest.yml
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}

unit_test:
    stage: test
    image : "$CONTAINER_IMAGE"
    variables:
      XDEBUG_ON: "true"
    services:
        - mysql
    script:
        - cp /var/www/pastell/ci-resources/LocalSettings.php /var/www/pastell/
        - php /var/www/pastell/ci-resources/wait-for-mysql-start.php
        - /usr/local/lib/composer/vendor/bin/phpunit --coverage-text --colors=never -c /var/www/pastell/test/PHPUnit/phpunit.xml

acceptance_test:
    stage: test
    image :  "$CONTAINER_IMAGE"
    services:
        - mysql
    variables:
        MYSQL_HOST: 'mysql'
        MYSQL_PORT: '3306'
    script:
        - cp /var/www/pastell/ci-resources/LocalSettings.php /var/www/pastell/
        - php /var/www/pastell/ci-resources/wait-for-mysql-start.php
        - php /var/www/pastell/ci-resources/init-docker.php
        - service apache2 start
        - /usr/local/lib/composer/vendor/bin/codecept run -c /var/www/pastell/test/codeception

staging:
    stage: staging
    only:
        - develop
    image: kroniak/ssh-client
    variables:
        GIT_STRATEGY: none
    script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh -tt gitlab@pastell2.test.libriciel.fr "docker login -u gitlab-ci-token -p '$CI_JOB_TOKEN' $CI_REGISTRY && docker pull $CONTAINER_IMAGE && cd /data/docker-file/ && docker-compose up -d"

release:
    stage: release
    only:
        - tags
    variables:
        GIT_STRATEGY: none
    script:
        - echo "TODO"
        #TODO envoyer vers le FTP