image: docker:latest


stages:
    - build
    - test

build:
  stage: build
  tags:
    - docker-build
  script:
    - export IMAGE_TAG="${CI_BUILD_REF_NAME}-${CI_BUILD_REF}-test"
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

services:
- mysql

variables:
    MYSQL_DATABASE: pastell_test
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"

test:
    stage: test
    script:
        - docker run $CONTAINER_TEST_IMAGE ext/composer/vendor/phpunit/phpunit/phpunit --coverage-text --colors=never -c test/PHPUnit/phpunit.xml


