image: docker:latest

stages:
    - staging
    - build
    - test
    - release


build:
  stage: build
  tags:
    - docker-build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t ${CONTAINER_TEST_IMAGE} .
    - docker push ${CONTAINER_TEST_IMAGE}

services:
    - mysql

variables:
    CONTAINER_TEST_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}_test"
    CONTAINER_RELEASE_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    MYSQL_DATABASE: pastell_test
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"

test:
    stage: test
    image : "$CONTAINER_TEST_IMAGE"
    script:
        - cp /var/www/pastell/ci-resources/LocalSettings.php /var/www/pastell/
        - php /var/www/pastell/ci-resources/wait-for-mysql-start.php
        - /usr/local/lib/composer/vendor/bin/phpunit --coverage-text --colors=never -c /var/www/pastell/test/PHPUnit/phpunit.xml

acceptance_test:
    stage: test
    image :  "$CONTAINER_TEST_IMAGE"
    variables:
        MYSQL_HOST: 'mysql'
        MYSQL_PORT: '3306'
    script:
        - cp /var/www/pastell/ci-resources/LocalSettings.php /var/www/pastell/
        - php /var/www/pastell/ci-resources/wait-for-mysql-start.php
        - php /var/www/pastell/ci-resources/init-docker.php
        - service apache2 start
        - /usr/local/lib/composer/vendor/bin/codecept run -c /var/www/pastell/test/codeception

release:
    stage: release
    tags:
        - docker-build
    script:
        - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
        - docker pull  "$CONTAINER_TEST_IMAGE"
        - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE"
        - echo "Push to $CONTAINER_RELEASE_IMAGE"
        - docker push $CONTAINER_RELEASE_IMAGE

staging:
    stage: staging
    image: kroniak/ssh-client
    script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh -t gitlab@pastell2.test.libriciel.fr "docker login -u gitlab-ci-token -p '$CI_JOB_TOKEN' $CI_REGISTRY && docker pull gitlab.libriciel.fr:4567/pastell/pastell:master && cd /data/docker-file/ && docker-compose up -d"
