image: docker:latest

stages:
    - build
    - test

build:
  stage: build
  tags:
    - docker-build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

services:
    - mysql

variables:
    MYSQL_DATABASE: pastell_test
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    IMAGE_TAG: "${CI_BUILD_REF_NAME}-${CI_BUILD_REF}-test"

test:
    stage: test
    #image : "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    image: php:5.6
    script:
        - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales
        - sed -i -e 's/# fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/' /etc/locale.gen
        - echo 'LANG="fr_FR.UTF-8"'>/etc/default/locale
        - dpkg-reconfigure --frontend=noninteractive locales
        - update-locale LANG=fr_FR.UTF-8
        - pecl install xdebug
        - docker-php-ext-install pdo pdo_mysql bcmath
        - docker-php-ext-enable xdebug
        - cp ci-resources/LocalSettings.php .
        - cat /var/www/pastell/LocalSettings.php
        - ext/composer/vendor/phpunit/phpunit/phpunit --coverage-text --colors=never -c test/PHPUnit/phpunit.xml

