
image: php:5.6

before_script:
- docker-php-ext-install pdo pdo_mysql

services:
- mysql

variables:
    MYSQL_DATABASE: pastell_test
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"

test:
    script:
        - ext/composer/vendor/phpunit/phpunit/phpunit -c test/PHPUnit/phpunit.xml


