image: docker:latest


variables:
    CI_DEBUG_TRACE: "true"
    CONTAINER_TEST_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}_test"
    TOTO: "toto"

stages:
    - build
    - test

build:
  stage: build
  tags:
    - docker-build
  script:
    - echo ${TOTO}
    - echo ${CONTAINER_TEST_IMAGE}
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t ${CONTAINER_TEST_IMAGE} .
    - docker push ${CONTAINER_TEST_IMAGE}
  variables:
    CI_DEBUG_TRACE: "true"
    CONTAINER_TEST_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}_test"
    TOTO: "toto"
services:
- mysql

variables:
    MYSQL_DATABASE: pastell_test
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"

test:
    stage: test
    script:
        - docker run $CONTAINER_TEST_IMAGE ext/composer/vendor/phpunit/phpunit/phpunit --coverage-text --colors=never -c test/PHPUnit/phpunit.xml


