
image: php:5.6

before_script:
- apt-get update && apt-get install -y locales
- docker-php-ext-install pdo pdo_mysql bcmath
- locale-gen fr_FR.UTF-8 && dpkg-reconfigure locales
- cp ci-resources/LocalSettings.php .

services:
- mysql

variables:
    MYSQL_DATABASE: pastell_test
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"

test:
    script:
        - ext/composer/vendor/phpunit/phpunit/phpunit -c test/PHPUnit/phpunit.xml


