image: docker:latest

stages:
    - build
    - test

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_ID:$CI_BUILD_REF_NAME_test

before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

services:
- mysql

variables:
    MYSQL_DATABASE: pastell_test
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"

test:
    stage: test
    script:
        - docker run $CONTAINER_TEST_IMAGE ext/composer/vendor/phpunit/phpunit/phpunit --coverage-text --colors=never -c test/PHPUnit/phpunit.xml


