image: docker:latest

stages:
    - build
    - test

build:
  stage: build
  tags:
    - docker-build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

services:
    - mysql

variables:
    IMAGE_TAG: "${CI_BUILD_REF_NAME}-${CI_BUILD_REF}-test"
    MYSQL_DATABASE: pastell_test
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"

test:
    stage: test
    image : "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    script:
        - cp ci-resources/LocalSettings.php .
        - ext/composer/vendor/phpunit/phpunit/phpunit --coverage-text --colors=never -c test/PHPUnit/phpunit.xml
