version: '3.5'

services:
    web:
        image: gitlab.libriciel.fr:4567/pastell/pastell:2.0.X
        ports:
            - 443:443
            - 80:80
        volumes:
            - ${LETSENCRYPT_DATADIR}:/etc/letsencrypt
        environment:
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            LETSENCRYPT_DOMAIN1: ${LETSENCRYPT_DOMAIN}


