version: '3.0'

services:
    web:
        image: gitlab.libriciel.fr:4567/pastell/pastell:master
        links:
            - db
        env_file:
            - .env

    db:
        image: mysql
        env_file:
            - .env


# Initialisation :
# docker-compose exec web php /var/www/pastell/ci-resources/init-docker.php