version: '3.7'

#TODO -- Voir comment éviter un copier/coller depuis docker-compose.yml


services:
    web:
        image: registry.libriciel.fr:443/public/plateforme/pastell:canary
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ${LETSENCRYPT_DATADIR}:/etc/letsencrypt
            - ${PASTELL_EXTENSION_PATH:-../}:/data/extensions/
            - ${WORKSPACE_VOLUME:-app_workspace}:/data/workspace
            - ${PASTELL_SSL_CERTIFICAT:-app_certificate}:/data/certificate
            - ${PASTELL_SESSION:-app_session}:/var/lib/php/session
        networks:
            - internal_services
            - default
        links:
            - db
            - redis
        environment:
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            LETSENCRYPT_DOMAIN1: ${LETSENCRYPT_DOMAIN}
            REDIS_SERVER: redis
            REDIS_PORT: 6379
            SMTP_SERVER: ${SMTP_SERVER:-}
            SMTP_PORT: ${SMTP_PORT:-25}
            PLATEFORME_MAIL: ${PLATEFORME_MAIL:-noreply@pastell}
            WEBSEC_BASE: ${WEBSEC_BASE:-https://localhost:8443}
            AUTHENTICATION_WITH_CLIENT_CERTIFICATE: ${AUTHENTICATION_WITH_CLIENT_CERTIFICATE:-}
            PASTELL_ADMIN_LOGIN: ${PASTELL_ADMIN_LOGIN:-admin}
            PASTELL_ADMIN_PASSWORD: ${PASTELL_ADMIN_PASSWORD:-admin}
            PASTELL_ADMIN_EMAIL: ${PASTELL_ADMIN_EMAIL:-noreply@noreply.com}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-pastell}
            MYSQL_HOST: db
            PASTELL_SITE_BASE: ${PASTELL_SITE_BASE:-https://localhost:8443}
            MYSQL_HOST_TEST: ${MYSQL_HOST_TEST:-db_test}

    db:
        image: mysql:5.7
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-pastell}
        volumes:
            - ${MYSQL_DATADIR:-db_datadir}:/var/lib/mysql/

    redis:
        image: redis

    moustache:
        image: gitlab.libriciel.fr:4567/outils/moustache:master
        environment:
            DEV_MODE: 'true'
        ports:
            - "5000:5000"