version: '3.5'

services:
    web:
        image: gitlab.libriciel.fr:4567/pastell/pastell:master
        ports:
            - 443:443
            - 80:80
        volumes:
            - ${LETSENCRYPT_DATADIR}:/etc/letsencrypt
        environment:
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            LETSENCRYPT_DOMAIN1: ${LETSENCRYPT_DOMAIN}

    moustache:
        image: gitlab.libriciel.fr:4567/outils/moustache:master
        environment:
            DEV_MODE: 'true'
        ports:
            - 5000:5000

    pes-viewer:
        image: gitlab.libriciel.fr:4567/libriciel/pole-signature/i-parapheur-v5/pes-viewer:1.2.10
        ports:
            - 8888:8888