version: '3.0'

services:
    web:
      image: gitlab.libriciel.fr:4567/pastell/pastell
      links:
        - db

#TODO lier des variables d'environnement pour remplir le fichier LocalSettings.php

    db:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_DATABASE: pastell

# Initialisation :
# docker-compose exec web php /var/www/pastell/ci-resources/init-docker.php