version: '3.7'

services:
  webubuntu22:
    image: pastell:ubuntu22
    build:
      context: .
      dockerfile: Dockerfile-ubuntu22
      target: pastell_dev
    links:
      - db
      - redis
    volumes:
      - ${PASTELL_EXTENSION_PATH:-../}:/data/extensions/
      - ${WORKSPACE_VOLUME:-app_workspace}:/data/workspace
      - ${PASTELL_SSL_CERTIFICAT:-app_certificate}:/data/certificate
      - ${PASTELL_SESSION:-app_session}:/var/lib/php/session
      - ./ubuntu22:/var/www/pastell/ubuntu22
    environment:
      REDIS_SERVER: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      SMTP_SERVER: ${SMTP_SERVER:-}
      SMTP_PORT: ${SMTP_PORT:-25}
      PLATEFORME_MAIL: ${PLATEFORME_MAIL:-noreply@pastell}
      WEBSEC_BASE: ${WEBSEC_BASE:-https://localhost:8443}
      AUTHENTICATION_WITH_CLIENT_CERTIFICATE: ${AUTHENTICATION_WITH_CLIENT_CERTIFICATE:-}
      PASTELL_ADMIN_LOGIN: ${PASTELL_ADMIN_LOGIN:-admin}
      PASTELL_ADMIN_PASSWORD: ${PASTELL_ADMIN_PASSWORD:-admin}
      PASTELL_ADMIN_EMAIL: ${PASTELL_ADMIN_EMAIL:-noreply@noreply.com}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-pastell}
      MYSQL_HOST: db
      PASTELL_SITE_BASE: ${PASTELL_SITE_BASE:-https://localhost:8443}
      MYSQL_HOST_TEST: ${MYSQL_HOST_TEST:-db_test}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-}
      LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN:-}
    ports:
      - "${WEB_HTTP_PORT:-8000}:80"
      - "${WEB_HTTPS_PORT:-8443}:443"