version: '3.7'

services:
    web:
        image: registry.libriciel.fr:443/public/plateforme/pastell:canary
        build:
            context: .
            target: pastell_prod
            args:
                GITHUB_API_TOKEN: ${GITHUB_API_TOKEN:-}
        links:
            - db
            - redis
        volumes:
            - ${PASTELL_EXTENSION_PATH:-../}:/data/extensions/
            - ${WORKSPACE_VOLUME:-app_workspace}:/data/workspace
            - ${PASTELL_SSL_CERTIFICAT:-app_certificate}:/data/certificate
            - ${PASTELL_SESSION:-app_session}:/var/lib/php/session
        environment:
            REDIS_SERVER: ${REDIS_HOST:-redis}
            REDIS_PORT: ${REDIS_PORT:-6379}
            SMTP_SERVER: ${SMTP_SERVER:-}
            SMTP_PORT: ${SMTP_PORT:-25}
            PLATEFORME_MAIL: ${PLATEFORME_MAIL:-noreply@pastell}
            WEBSEC_BASE: ${WEBSEC_BASE:-https://localhost:8443}
            AUTHENTICATION_WITH_CLIENT_CERTIFICATE: ${AUTHENTICATION_WITH_CLIENT_CERTIFICATE:-}
            PASTELL_ADMIN_LOGIN: ${PASTELL_ADMIN_LOGIN:-admin}
            PASTELL_ADMIN_PASSWORD: ${PASTELL_ADMIN_PASSWORD:-admin}
            PASTELL_ADMIN_EMAIL: ${PASTELL_ADMIN_EMAIL:-noreply@noreply.com}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-pastell}
            MYSQL_HOST: db
            PASTELL_SITE_BASE: ${PASTELL_SITE_BASE:-https://localhost:8443}
            MYSQL_HOST_TEST: ${MYSQL_HOST_TEST:-db_test}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-}
            LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN:-}
        ports:
            - "${WEB_HTTP_PORT:-8000}:80"
            - "${WEB_HTTPS_PORT:-8443}:443"
    db:
        image: mysql:5.7
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
          MYSQL_USER: ${MYSQL_USER:-user}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
          MYSQL_DATABASE: ${MYSQL_DATABASE:-pastell}
        volumes:
            - ${MYSQL_DATADIR:-db_datadir}:/var/lib/mysql/

    redis:
        image: redis:6.2.6

    seda-generator:
        image: 'registry.libriciel.fr:443/public/plateforme/seda-generator:0.8.1'
        restart: unless-stopped
        volumes:
            - '/etc/localtime:/etc/localtime:ro'

    cloudooo:
        restart: unless-stopped
        image: 'registry.libriciel.fr/public/actes/cloudooo:7.1.0'

    pes-viewer:
        restart: unless-stopped
        image: 'registry.libriciel.fr/public/signature/pes-viewer:1.4.0'

    crypto:
        restart: unless-stopped
        image: 'registry.libriciel.fr:443/public/signature/crypto:2.3.1'

    libersign:
        restart: unless-stopped
        image: 'registry.libriciel.fr:443/public/signature/libersign:1.11.4'


volumes:
    db_datadir:
    app_workspace:
    app_certificate:
    app_session:
    db_datadir_test:
