version: '2.0'

services:
    web:
        image: gitlab.libriciel.fr:4567/pastell/pastell:master
        ports:
            - 443:443
            - 80:80
        volumes:
            - ${LETSENCRYPT_DATADIR}:/etc/letsencrypt
        environment:
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            LETSENCRYPT_DOMAIN1: ${LETSENCRYPT_DOMAIN}

    pastell_chorus_pro:
        image: gitlab.libriciel.fr:4567/pastell/pastell-chorus-pro
        volumes:
            - ${PASTELL_EXTENSION_PATH}/pastell-cpp:/data/extensions/pastell-chorus-pro

    pastell_glaneur_doc:
        image: gitlab.libriciel.fr:4567/pastell/pastell-glaneur-doc
        volumes:
            - ${PASTELL_EXTENSION_PATH}/pastell-glaneur-doc:/data/extensions/pastell-glaneur-doc

    pastell-actes-specifique:
        image: gitlab.libriciel.fr:4567/pastell/pastell-actes-specifique
        volumes:
            - ${PASTELL_EXTENSION_PATH}/pastell-actes-specifique:/data/extensions/pastell-actes-specifique

    pastell_cdg59:
        image: gitlab.libriciel.fr:4567/pastell/clients/pastell-cdg59
        volumes:
            - ${PASTELL_EXTENSION_PATH}/pastell-cdg59:/data/extensions/pastell-cdg59