version: '2.0'

services:
    web:
        image: gitlab.libriciel.fr:4567/pastell/pastell:master
        links:
            - db
        env_file:
            - .env
        volumes:
            - ${WORKSPACE_VOLUME}:/data/workspace
            - ${PASTELL_EXTENSION_PATH}:/data/extensions/

    db:
        image: mysql

        env_file:
            - .env
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ${MYSQL_DATADIR}:/var/lib/mysql/
