version: '3.5'

services:
    web:
        links:
            - db
            - redis
            - cloudooo
        env_file:
            - .env
        volumes:
            - ${WORKSPACE_VOLUME}:/data/workspace
            - ${LOG_VOLUME}:/data/log
            - ${PASTELL_EXTENSION_PATH}:/data/extensions/
            - ${PASTELL_SESSION}:/var/lib/php/session
            - ${PASTELL_SSL_CERTIFICAT}:/etc/apache2/ssl/
            - ${PASTELL_GLANEUR}:/data/glaneur/
        environment:
            REDIS_SERVER: redis
            REDIS_PORT: 6379
            SMTP_SERVER: ${SMTP_SERVER}
            SMTP_PORT: ${SMTP_PORT}
            PLATEFORME_MAIL: ${PLATEFORME_MAIL}
            WEBSEC_BASE: ${WEBSEC_BASE}
            AUTHENTICATION_WITH_CLIENT_CERTIFICATE: ${AUTHENTICATION_WITH_CLIENT_CERTIFICATE:-}
            PASTELL_ADMIN_LOGIN: ${PASTELL_ADMIN_LOGIN:-admin}
            PASTELL_ADMIN_PASSWORD: ${PASTELL_ADMIN_PASSWORD:-admin}
            PASTELL_ADMIN_EMAIL: ${PASTELL_ADMIN_EMAIL:-noreply@noreply.com}
    db:
        image: mysql:5.7
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

        env_file:
            - .env
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ${MYSQL_DATADIR}:/var/lib/mysql/

    redis:
        image: redis

    cloudooo:
        image: gitlab.libriciel.fr:4567/docker/cloudooo:master

    seda-generator:
        image: registry.libriciel.fr:443/public/plateforme/seda-generator:0.6.0
        ports:
            - ${SEDA_GENERATOR_PORT:-8021}:80
        volumes:
            - "/etc/localtime:/etc/localtime:ro"



