version: '2.0'

services:
    web:
        image: gitlab.libriciel.fr:4567/pastell/pastell:develop
        ports:
            - 443:443
            - 80:80

    letsencrypt:
        image:  blacklabelops/letsencrypt
        environment:
            - LETSENCRYPT_HTTPS_ENABLED: false
            - LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            - LETSENCRYPT_DOMAIN1: ${LETSENCRYPT_DOMAIN}
        volume:
            - ${LETSENCRYPT_DATADIR}:/etc/letsencrypt

