version: '2.0'

services:
    web:
        build: .
        ports:
            - "8000:80"
            - "8443:443"
        volumes:
            - .:/var/www/pastell

    phpunit:
        build: .
        environment:
            PASTELL_SITE_BASE: ${PASTELL_SITE_BASE_TEST}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER_TEST}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD_TEST}
            MYSQL_DATABASE: ${MYSQL_DATABASE_TEST}
            MYSQL_HOST: ${MYSQL_HOST_TEST}
            REDIS_HOST: redis
        volumes:
            - .:/var/www/pastell

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8001:80"
        env_file:
            - .env

    web_test:
        build: .
        ports:
            - "8003:443"
        volumes:
            - .:/var/www/pastell
        env_file:
            - .env
        links:
            - redis:redis
            - db_test:db_test
        environment:
            PASTELL_SITE_BASE: ${PASTELL_SITE_BASE_TEST}
            PASTELL_SITE_BASE_TEST: ${PASTELL_SITE_BASE_TEST}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER_TEST}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD_TEST}
            MYSQL_DATABASE: ${MYSQL_DATABASE_TEST}
            MYSQL_HOST: ${MYSQL_HOST_TEST}
            MYSQL_USER_TEST: ${MYSQL_USER_TEST}
            MYSQL_PASSWORD_TEST: ${MYSQL_PASSWORD_TEST}
            MYSQL_DATABASE_TEST: ${MYSQL_DATABASE_TEST}
            MYSQL_HOST_TEST: ${MYSQL_HOST_TEST}
            REDIS_SERVER: redis

    db_test:
        image: mysql

        env_file:
            - .env
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER_TEST}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD_TEST}
          MYSQL_DATABASE: ${MYSQL_DATABASE_TEST}
        volumes:
            - ${MYSQL_DATADIR_TEST}:/var/lib/mysql/
        ports:
          - "13306:3306"

    phpmyadmin_test:
        image: phpmyadmin/phpmyadmin
        links:
            - db_test:db_test
        ports:
            - "8004:80"
        env_file:
            - .env

    redis:
        ports:
            - 6379:6379



