version: '3.0'

services:
    web:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/pastell
            - ../pastell-extension-adullact-projet:/data/extensions/pastell-extension-adullact-projet


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8001:80"
        env_file:
            - .env

    db_test:
        image: mysql
        ports:
            - "8306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_DATABASE: pastell_test

    phpunit:
        build: .
        links:
            - db_test
        volumes:
            - .:/var/www/pastell
        env_file:
            - .env

