version: '2.0'

services:
    web:
        links:
            - db
            - redis
        env_file:
            - .env
        volumes:
            - ${WORKSPACE_VOLUME}:/data/workspace
            - ${PASTELL_EXTENSION_PATH}:/data/extensions/
            - ${PASTELL_SESSION}:/var/lib/php/session
            - ${PASTELL_SSL_CERTIFICAT}:/etc/apache2/ssl/
        environment:
            REDIS_SERVER: redis
            REDIS_PORT: 6379
            SMTP_SERVER: ${SMTP_SERVER}
            SMTP_PORT: ${SMTP_PORT}

    db:
        image: mysql

        env_file:
            - .env
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ${MYSQL_DATADIR}:/var/lib/mysql/

    redis:
        image: redis



