version: '2.0'

services:
    web:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/pastell

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8001:80"
        env_file:
            - .env

    db_test:
        image: mysql
        ports:
            - "8306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER_TEST}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD_TEST}
            MYSQL_DATABASE: ${MYSQL_DATABASE_TEST}

    phpunit:
        build: .
        ports:
            - "8003:80"
        links:
            - db_test
        volumes:
            - .:/var/www/pastell
        env_file:
            - .env

