version: '2.0'

services:
    web:
        image: gitlab.libriciel.fr:4567/pastell/pastell:master
        ports:
            - 443:443
            - 80:80
        volumes:
            - ${LETSENCRYPT_DATADIR}:/etc/letsencrypt
            - pastell-cpp:/data/extensions-tmp/pastell-cpp
            - pastell-glaneur-doc:/data/extensions-tmp/pastell-glaneur-doc
            - pastell-actes-specifique:/data/extensions-tmp/pastell-actes-specifique
            - pastell-cdg59:/data/extensions-tmp/pastell-cdg59
        environment:
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            LETSENCRYPT_DOMAIN1: ${LETSENCRYPT_DOMAIN}


    pastell_chorus_pro:
        image: gitlab.libriciel.fr:4567/pastell/pastell-chorus-pro
        volumes:
            - pastell-cpp:/data/extensions/pastell-chorus-pro

    pastell_glaneur_doc:
        image: gitlab.libriciel.fr:4567/pastell/pastell-glaneur-doc
        volumes:
            - pastell-glaneur-doc:/data/extensions/pastell-glaneur-doc

    pastell-actes-specifique:
        image: gitlab.libriciel.fr:4567/pastell/pastell-actes-specifique
        volumes:
            - pastell-actes-specifique:/data/extensions/pastell-actes-specifique

    pastell_cdg59:
        image: gitlab.libriciel.fr:4567/pastell/pastell-cdg59
        volumes:
            - pastell-cdg59:/data/extensions/pastell-cdg59

volumes:
     pastell-cpp:
     pastell-glaneur-doc:
     pastell-cdg59:
     pastell-actes-specifique:

