version: '3.0'

services:
    web:
        image: gitlab.libriciel.fr:4567/pastell/pastell:master
        links:
            - db
        env_file:
            - .env

    db:
        image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_USER: user
          MYSQL_PASSWORD: user
          MYSQL_DATABASE: pastell


# Initialisation :
# docker-compose exec web php /var/www/pastell/ci-resources/init-docker.php