
services:
  crypto:
    restart: unless-stopped
    image: 'registry.libriciel.fr:443/public/signature/crypto:2.3.1'
    deploy:
      resources:
        limits:
          memory: 1G

  libersign:
    restart: unless-stopped
    image: 'registry.libriciel.fr:443/public/signature/libersign:1.11.4'