version: '3.7'

services:
    web:
        image: registry.libriciel.fr:443/public/plateforme/pastell:canary
        build:
            context: ..
            target: pastell_prod
            args:
                GITHUB_API_TOKEN: ${GITHUB_API_TOKEN:-}
        read_only: true
        stop_grace_period: 60s
        stop_signal: SIGTERM
        links:
            - db
            - redis
        tmpfs:
            - /data/config:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /data/run:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /data/lock:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /data/html_purifier:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /var/run:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /var/www/pastell/var:mode=770,uid=${UID:-33},gid=${GID:-33}
        volumes:
            - ${PASTELL_EXTENSION_PATH:-../../}:/data/extensions/
            - ${WORKSPACE_VOLUME:-app_workspace}:/data/workspace
            - ${PASTELL_SSL_CERTIFICAT:-app_certificate}:/data/certificate
            - ${PASTELL_SESSION:-app_session}:/var/lib/php/session
            - ${LETSENCRYPT_DATADIR:-letsencrypt_datadir}:/etc/letsencrypt
            - ${LOGS_PATH:-logs_datadir}:/data/log
            - ${TMP_PATH:-tmp_datadir}:/tmp
            - ${UPLOAD_CHUNK_PATH:-upload_chunk_datadir}:/data/upload_chunk
        environment:
            REDIS_SERVER: ${REDIS_HOST:-redis}
            REDIS_PORT: ${REDIS_PORT:-6379}
            PLATEFORME_MAIL: ${PLATEFORME_MAIL:-noreply@paste.ll}
            WEBSEC_BASE: ${WEBSEC_BASE:-https://localhost:8443/mailsec/}
            AUTHENTICATION_WITH_CLIENT_CERTIFICATE: ${AUTHENTICATION_WITH_CLIENT_CERTIFICATE:-}
            PASTELL_ADMIN_LOGIN: ${PASTELL_ADMIN_LOGIN:-admin}
            PASTELL_ADMIN_PASSWORD: ${PASTELL_ADMIN_PASSWORD:-admin}
            PASTELL_ADMIN_EMAIL: ${PASTELL_ADMIN_EMAIL:-noreply@noreply.com}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-pastell}
            MYSQL_HOST: db
            PASTELL_SITE_BASE: ${PASTELL_SITE_BASE:-https://localhost:8443}
            MYSQL_HOST_TEST: ${MYSQL_HOST_TEST:-db_test}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-}
            LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN:-}
            SENTRY_DSN: ${SENTRY_DSN:-}
            SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT:-dev}
            MAILER_DSN: ${MAILER_DSN:-null://null}
            ADMIN_EMAIL: ${ADMIN_EMAIL:-noreply@noreply.com}
        ports:
            - "${WEB_HTTP_PORT:-8000}:8080"
            - "${WEB_HTTPS_PORT:-8443}:4443"
        user: "${UID:-33}:${GID:-33}"

    db:
        image: mysql:5.7
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
          MYSQL_USER: ${MYSQL_USER:-user}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
          MYSQL_DATABASE: ${MYSQL_DATABASE:-pastell}
        volumes:
            - ${MYSQL_DATADIR:-db_datadir}:/var/lib/mysql/

    redis:
        image: redis:6.2.6

    seda-generator:
        image: 'registry.libriciel.fr:443/public/plateforme/seda-generator:0.8.3'
        restart: unless-stopped
        volumes:
            - '/etc/localtime:/etc/localtime:ro'

    cloudooo:
        restart: unless-stopped
        image: 'registry.libriciel.fr/public/actes/cloudooo:7.1.0'

    pes-viewer:
        restart: unless-stopped
        image: 'registry.libriciel.fr/public/signature/pes-viewer:1.5.1'
        deploy:
            resources:
                limits:
                    memory: 1536M
        volumes:
            - ${PES_PJ_PATH:-/data/pesPJ}:/pesPJ/

    crypto:
        restart: unless-stopped
        image: 'registry.libriciel.fr:443/public/signature/crypto:2.3.1'
        deploy:
            resources:
                limits:
                    memory: 1G

    libersign:
        restart: unless-stopped
        image: 'registry.libriciel.fr:443/public/signature/libersign:1.11.4'


volumes:
    db_datadir:
    app_workspace:
    app_certificate:
    app_session:
    db_datadir_test:
    letsencrypt_datadir:
    logs_datadir:
    tmp_datadir:
    upload_chunk_datadir:
