services:
  web:
    environment:
      USE_VAULT_FOR_PASSWORD_STORAGE: ${USE_VAULT_FOR_PASSWORD_STORAGE:-true}
      VAULT_URL: ${VAULT_URL:-http://0.0.0.0:8200}
      VAULT_TOKEN: ${VAULT_TOKEN:-tdctoken}

  vault:
      image: hashicorp/vault
      container_name: pastell-vault-1
      cap_add:
        - IPC_LOCK
      ports:
        - 8200:8200
      environment:
        - VAULT_DEV_ROOT_TOKEN_ID=tdctoken
        - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      volumes:
        - ${HOME}/vault/data:/data
