services:
  web:
    environment:
      S3_URL: ${S3_URL:-http://minio:9000/}
      S3_KEY: ${S3_KEY:-minio-user-login}
      S3_SECRET: ${S3_SECRET:-minio-user-password}
      S3_BUCKET_JOURNAL: ${S3_BUCKET_JOURNAL:-journal-preuves}
      USE_EXTERNAL_STORAGE_FOR_JOURNAL_PROOF: ${USE_EXTERNAL_STORAGE_FOR_JOURNAL_PROOF:-false}

  minio:
    image: registry.libriciel.fr:443/public/plateforme/docker/minio:1.0.0
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio-root-user}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio-root-password}
      MINIO_DEFAULT_BUCKET: ${S3_BUCKET_JOURNAL:-first-bucket}
      MINIO_USER_LOGIN: ${S3_KEY:-minio-user-login}
      MINIO_USER_PASSWORD: ${S3_SECRET:-minio-user-password}
      MINIO_PORT_CONSOLE: ${MINIO_PORT_CONSOLE:-9001}
    volumes:
      - ${HOME}/minio/data:/data

