services:
  web:
    environment:
      S3_URL: ${S3_URL:-http://minio:9000/}
      S3_KEY: ${S3_KEY:-minioadmin}
      S3_SECRET: ${S3_SECRET:-minioadmin}
      S3_BUCKET_JOURNAL: ${S3_BUCKET_JOURNAL:-journal-preuves}
      USE_EXTERNAL_STORAGE_FOR_JOURNAL_PROOF: ${USE_EXTERNAL_STORAGE_FOR_JOURNAL_PROOF:-false}

  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${S3_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET:-minioadmin}
    volumes:
      - ${HOME}/minio/data:/data

