controllers:
  resource:
    path: ../src/Controller/
    namespace: Pastell\Controller
  type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation

legacy:
    resource: .
    type: legacy