#! /bin/bash
set -e

cat <<EOF
<?php

define("SITE_BASE","${PASTELL_SITE_BASE}");

define("BD_DSN","mysql:dbname=${MYSQL_DATABASE:-pastell};host=${MYSQL_HOST:-localhost};port=${MYSQL_PORT:-3306};charset=utf8");
define("BD_DBNAME","${MYSQL_DATABASE:-pastell}");
define("BD_USER","${MYSQL_USER:-user}");
define("BD_PASS","${MYSQL_PASSWORD:-user}");

define("BD_DSN_TEST","mysql:dbname=${MYSQL_DATABASE_TEST:-pastell_test};host=${MYSQL_HOST_TEST:-localhost};port=${MYSQL_PORT_TEST:-3306};charset=utf8");
define("BD_DBNAME_TEST","${MYSQL_DATABASE_TEST:-pastell_test}");
define("BD_USER_TEST","${MYSQL_USER_TEST:-user}");
define("BD_PASS_TEST","${MYSQL_PASSWORD_TEST:-user}");

define("WORKSPACE_PATH" , "/data/workspace");



EOF