#! /bin/bash
set -e

#Utiliser pour créer un fichier de settings en fonction des variables d'environnement (envoyé par Docker)

cat <<EOF
<?php

define("SITE_BASE","${PASTELL_SITE_BASE}");
define("WEBSEC_BASE","${WEBSEC_BASE}");

define("BD_DSN","mysql:dbname=${MYSQL_DATABASE:-pastell};host=${MYSQL_HOST:-localhost};port=${MYSQL_PORT:-3306};charset=utf8");
define("BD_DBNAME","${MYSQL_DATABASE:-pastell}");
define("BD_USER","${MYSQL_USER:-user}");
define("BD_PASS","${MYSQL_PASSWORD:-user}");

define("BD_DSN_TEST","mysql:dbname=${MYSQL_DATABASE_TEST:-pastell_test};host=${MYSQL_HOST_TEST:-localhost};port=${MYSQL_PORT_TEST:-3306};charset=utf8");
define("BD_DBNAME_TEST","${MYSQL_DATABASE_TEST:-pastell_test}");
define("BD_USER_TEST","${MYSQL_USER_TEST:-user}");
define("BD_PASS_TEST","${MYSQL_PASSWORD_TEST:-user}");

define("WORKSPACE_PATH" , "/data/workspace");

define("PLATEFORME_MAIL","${PLATEFORME_MAIL}");

define("REDIS_SERVER","${REDIS_SERVER}");
define("REDIS_PORT",${REDIS_PORT:-6379});

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

define("LOG_FILE","/data/log/pastell.log");
define("LOG_LEVEL", Monolog\Logger::${LOG_LEVEL:-INFO});

define("SENTRY_DSN", "${SENTRY_DSN}");
define("SENTRY_ENVIRONMENT", "${SENTRY_ENVIRONMENT:-dev}");

define("PES_VIEWER_URL", "${PES_VIEWER_URL:-${PASTELL_SITE_BASE}}");

define("MAILER_DSN", "${MAILER_DSN:-null://null}");


define("LIST_PACK", [
  "pack_chorus_pro" => ${PACK_CHORUS_PRO:-true},
  "pack_marche" => ${PACK_MARCHE:-true},
  "pack_urbanisme" => ${PACK_URBANISME:-true},
  "pack_test" => ${PACK_TEST:-true},
]);
EOF

env | grep '^TOGGLE_' | sed "s/^TOGGLE_\([^=]*\)=\(.*\)/\$feature_toggle[Pastell\\\Service\\\FeatureToggle\\\\\1::class] = \2;/g"
