#! /bin/bash
set -e

/bin/bash /var/www/pastell/ci-resources/docker-pastell-init > /etc/pastell/DockerSettings.php

#A mettre dans le dockerfile ?
usermod -s /bin/bash www-data

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

php /var/www/pastell/ci-resources/init-docker.php

exec "$@"
