#! /bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

usermod -s /bin/bash www-data
#hp /var/www/pastell/batch/pastell-daemon.php start

exec "$@"