#! /bin/bash
set -e

# Activation ou non de XDEBUG
if [ -z ${XDEBUG_ON} ]
then
    if [ -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ]
    then
        rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    fi
else
    docker-php-ext-enable xdebug
fi

/bin/bash /var/www/pastell/ci-resources/docker-pastell-init > /etc/pastell/DockerSettings.php

#A mettre dans le dockerfile ?
usermod -s /bin/bash www-data

# Génération fichier ssmtp.conf
/bin/bash /var/www/pastell/ci-resources/generate-ssmtp.conf.sh > /etc/ssmtp/ssmtp.conf


# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

su - www-data -c "php /var/www/pastell/ci-resources/init-docker.php"

exec "$@"
