#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          cloudooo
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
PIDFILE="/opt/cloudooo/pid/cloudooo.pid"
LOGFILE="/opt/cloudooo/log/cloudooo.log"
CONFIGFILE="/opt/cloudooo/conf/cloudooo.conf"

DAEMON="paster"
DAEMON_EXEC="/usr/local/bin/paster" #ligne de commande du programme, attention à l'extension .py.
daemon_OPT="serve $CONFIGFILE --daemon --pid-file $PIDFILE --log-file=$LOGFILE"  #argument à utiliser par le programme
DAEMONUSER="root" #utilisateur du programme
daemon_NAME="cloudooo" #Nom du programme (doit être identique à l'exécutable).
#Attention le script est un script bash, le script ne portera donc pas l'extension .py mais .sh.

PATH="/sbin:/bin:/usr/sbin:/usr/bin" #Ne pas toucher

test -x $DAEMON_EXEC || exit 0

. /lib/lsb/init-functions

d_start () {
log_daemon_msg "Starting system $daemon_NAME Daemon"
start-stop-daemon \
	--background \
	--name $daemon_NAME \
	--start \
	--quiet \
	--chuid $DAEMONUSER \
	--exec $DAEMON_EXEC \
	-- $daemon_OPT
	mkdir -p /tmp/cloudooo
log_end_msg $?
}

d_stop () {
log_daemon_msg "Stopping system $daemon_NAME Daemon"
start-stop-daemon --name $DAEMON --stop --retry 5 --quiet --name $DAEMON
killall /usr/lib/libreoffice/program/soffice.bin #FIX
log_end_msg $?
}

case "$1" in

    start|stop)
            d_${1}
            ;;

    restart|reload|force-reload)
                    d_stop
                    d_start
            ;;

    force-stop)
           d_stop
            killall -q $daemon_NAME || true
            sleep 2
            killall -q -9 $daemon_NAME || true
            ;;

    status)
            status_of_proc "$daemon_NAME" "$DAEMON_EXEC" "system-wide $daemon_NAME" && exit 0 || exit $?
            ;;
    *)
            echo "Usage: /etc/init.d/$daemon_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
            exit 1
            ;;
esac
exit 0

